// Auto-generated by scripts/generate-manifest.mjs
// DO NOT edit manually — run `npm run generate:manifest` to update.

export const prototypeGroups = [
  {
    "id": "Examples",
    "label": "Examples"
  },
  {
    "id": "Getting Started",
    "label": "Getting Started"
  }
];

export const prototypePages = [
  {
    "id": "dashboard",
    "path": "demos/examples/dashboard.html",
    "label": "Analytics Dashboard",
    "group": "Examples",
    "order": 1,
    "tags": [
      "dashboard",
      "charts",
      "analytics",
      "table"
    ],
    "description": "A sample analytics dashboard with stat cards, a bar chart, and a recent-events table",
    "hidden": false,
    "entry": false,
    "thumbnail": null
  },
  {
    "id": "contact-form",
    "path": "demos/examples/form.html",
    "label": "Contact Form",
    "group": "Examples",
    "order": 2,
    "tags": [
      "form",
      "input",
      "validation",
      "ui"
    ],
    "description": "A polished contact form with field validation and a success state",
    "hidden": false,
    "entry": false,
    "thumbnail": null
  },
  {
    "id": "getting-started",
    "path": "demos/getting-started/index.html",
    "label": "Getting Started",
    "group": "Getting Started",
    "order": 0,
    "tags": [
      "intro",
      "overview"
    ],
    "description": "Welcome page and overview of the HTML Demo Viewer",
    "hidden": false,
    "entry": true,
    "thumbnail": null
  }
];

export const prototypePageMap = {
  "demos/examples/dashboard.html": {
    "id": "dashboard",
    "path": "demos/examples/dashboard.html",
    "label": "Analytics Dashboard",
    "group": "Examples",
    "order": 1,
    "tags": [
      "dashboard",
      "charts",
      "analytics",
      "table"
    ],
    "description": "A sample analytics dashboard with stat cards, a bar chart, and a recent-events table",
    "hidden": false,
    "entry": false,
    "thumbnail": null
  },
  "demos/examples/form.html": {
    "id": "contact-form",
    "path": "demos/examples/form.html",
    "label": "Contact Form",
    "group": "Examples",
    "order": 2,
    "tags": [
      "form",
      "input",
      "validation",
      "ui"
    ],
    "description": "A polished contact form with field validation and a success state",
    "hidden": false,
    "entry": false,
    "thumbnail": null
  },
  "demos/getting-started/index.html": {
    "id": "getting-started",
    "path": "demos/getting-started/index.html",
    "label": "Getting Started",
    "group": "Getting Started",
    "order": 0,
    "tags": [
      "intro",
      "overview"
    ],
    "description": "Welcome page and overview of the HTML Demo Viewer",
    "hidden": false,
    "entry": true,
    "thumbnail": null
  }
};
